quarkus.application.name=fms-car-simulator
quarkus.http.port=8081
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
mp.messaging.outgoing.car-heartbeats.connector=smallrye-kafka
mp.messaging.outgoing.car-heartbeats.topic=fms.car.heartbeats
mp.messaging.outgoing.car-heartbeats.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.trip-events.connector=smallrye-kafka
mp.messaging.incoming.trip-events.topic=fms.trip.events
mp.messaging.incoming.trip-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.trip-events.group.id=fms-simulator-group
mp.messaging.incoming.trip-events.auto.offset.reset=latest
simulator.city.lat.min=37.95
simulator.city.lat.max=38.05
simulator.city.lon.min=23.70
simulator.city.lon.max=23.80
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.log.level=INFO
