quarkus.application.name=fms-fleet-api
quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:fms_user}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:fms_pass}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/fms_db}
quarkus.datasource.jdbc.max-size=16
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
mp.messaging.outgoing.trip-events.connector=smallrye-kafka
mp.messaging.outgoing.trip-events.topic=fms.trip.events
mp.messaging.outgoing.trip-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
quarkus.smallrye-openapi.info-title=Fleet Management API
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.log.level=INFO